name: lnurl_quests

services:
  python_api:
    container_name: lnurl_quests_python_api
    build:
      context: ./python_app
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./python_app/app:/app
    restart: unless-stopped
    networks:
      - lnurlWithdraw
    command: uvicorn main:app --host 0.0.0.0 --port 5000

  nestjs_api:
    container_name: lnurl_quests_nestjs_api
    build:
      context: ./nestjs_app
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - python_api
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - lnurlWithdraw

networks:
  lnurlWithdraw: