name: lnurl_quests

services:
  mongodb:
    image: mongo:latest
    container_name: lnurl_quests_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: lnurl-quests
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - lnurlQuests
    command: ["--auth", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  nestjs_api:
    container_name: lnurl_quests_nestjs_api
    build:
      context: ./nestjs_api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./nestjs_api:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run start:debug
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - lnurlQuests

volumes:
  mongodb_data:
    name: lnurl-quests-mongodb-data

networks:
  lnurlQuests: